# You likely have some configuration above

homeassistant: # <- Look for this one. If it doesn't exist, create it
  packages: !include_dir_named packages/ # Includes every package that is inside the packages/ directory
  ## Warning! Please pay attention to the indentation!

# You likely have some more configuration below